---
title: "Fundamentals of the Tidyverse"
author: '[Sergio Uribe](https://sergiouri.be)'
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    code_folding: hide
---



```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE, out.width="75%")
# Use include=TRUE for the chunks to be displayed
```

install.packages(c("tidyverse", "palmerpenguins", "gganimate", "gifski", "leaflet"))
 # Packages
```{r}
# if (!require("pacman")) install.packages("pacman") # run in a new installation
pacman::p_load(tidyverse,  # for data science
               palmerpenguins,    # 
               gganimate,         # 
               gifski, 
               leaflet
)
```

Graph theme
```{r}
# theme_set(theme_minimal())
```


# 1. Basic data visualization and summarizing.
# 2. Data wrangling.
# 3. Handling special variable types.
# 4. Enhance your visualization.
